/*
 *  Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/** 
 * @author Euguene Ostrovsky
 * @version $Revision: 1.1.2.1.4.6 $
 */  

/*
 * THE FILE HAS BEEN AUTOGENERATED BY INTEL IJH TOOL.
 * Please be aware that all changes made to this file manually
 * will be overwritten by the tool if it runs again.
 */

#include <jni.h>


/* Header for class com.ibm.oti.vm.VM */

#ifndef _COM_IBM_OTI_VM_VM_H
#define _COM_IBM_OTI_VM_VM_H

#ifdef __cplusplus
extern "C" {
#endif


/* Native methods */

/*
 * Method: com.ibm.oti.vm.VM.getClassLoader(Ljava/lang/Class;)Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL
Java_com_ibm_oti_vm_VM_getClassLoader(JNIEnv *, jclass, 
    jclass);


#ifdef __cplusplus
}
#endif

#endif /* _COM_IBM_OTI_VM_VM_H */

