/*
 *  Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * @author Serguei S.Zapreyev
 * @version $Revision: 1.1.2.1.4.4 $
 */

/*
 * THIS HEADER FILE WAS GENERATED BY INTEL IJH TOOL.
 * Please be aware that all the changes of this file
 * will be overwritten by the tool when it runs again.
 */

#include <jni.h>


/* Header for class java.lang.ref.Reference */

#ifndef _JAVA_LANG_REF_REFERENCE_H
#define _JAVA_LANG_REF_REFERENCE_H

#ifdef __cplusplus
extern "C" {
#endif


/* Native methods */

/*
 * Method: java.lang.ref.Reference.initReference(Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL
Java_java_lang_ref_Reference_initReference(JNIEnv *, jobject, 
    jobject);


#ifdef __cplusplus
}
#endif

#endif /* _JAVA_LANG_REF_REFERENCE_H */

