HYTHR_0.1 {
	global :
	hythread_monitor_init_with_name;
	hythread_monitor_destroy;
	hythread_monitor_try_enter;
	hythread_monitor_enter;
	hythread_monitor_notify_all;
	hythread_attach;
	hythread_create;
	hythread_detach;
	hythread_global;
        hythread_self;
	hythread_tls_alloc;
	hythread_tls_free;
	hythread_tls_set;
        hythread_monitor_wait;
        hythread_monitor_exit;
	hythread_tls_get;
	local : *;
};
