/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shutdown_TestDaemonOnWait_WorkerThread */

#ifndef _Included_shutdown_TestDaemonOnWait_WorkerThread
#define _Included_shutdown_TestDaemonOnWait_WorkerThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shutdown_TestDaemonOnWait_WorkerThread
 * Method:    callJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_shutdown_TestDaemonOnWait_00024WorkerThread_callJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
