/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shutdown_TestInterrupt */

#ifndef _Included_shutdown_TestInterrupt
#define _Included_shutdown_TestInterrupt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shutdown_TestInterrupt
 * Method:    sendInterrupt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_shutdown_TestInterrupt_sendInterrupt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
