/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shutdown_TestNativeAllocation_WorkerThread */

#ifndef _Included_shutdown_TestNativeAllocation_WorkerThread
#define _Included_shutdown_TestNativeAllocation_WorkerThread
#ifdef __cplusplus
extern "C" {
#endif
#undef shutdown_TestNativeAllocation_WorkerThread_MIN_PRIORITY
#define shutdown_TestNativeAllocation_WorkerThread_MIN_PRIORITY 1L
#undef shutdown_TestNativeAllocation_WorkerThread_NORM_PRIORITY
#define shutdown_TestNativeAllocation_WorkerThread_NORM_PRIORITY 5L
#undef shutdown_TestNativeAllocation_WorkerThread_MAX_PRIORITY
#define shutdown_TestNativeAllocation_WorkerThread_MAX_PRIORITY 10L
/*
 * Class:     shutdown_TestNativeAllocation_WorkerThread
 * Method:    callJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_shutdown_TestNativeAllocation_00024WorkerThread_callJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
