/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shutdown_TestFatalError */

#ifndef _Included_shutdown_TestFatalError
#define _Included_shutdown_TestFatalError
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shutdown_TestFatalError
 * Method:    sendFatalError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_shutdown_TestFatalError_sendFatalError
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
